# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/html2slim/all/html2slim.rbi
#
# html2slim-0.2.0
module HTML2Slim
  def self.convert!(input, format = nil); end
end
module SlimText
  def to_slim(lvl = nil); end
end
class Hpricot::CData < Anonymous_Object_24
  include SlimText
end
class Hpricot::BogusETag < Anonymous_Object_25
  def to_slim(lvl = nil); end
end
class Hpricot::Text < Anonymous_Object_24
  include SlimText
end
class Hpricot::Comment < Anonymous_Object_24
  def to_slim(lvl = nil); end
end
class Hpricot::DocType < Anonymous_Object_25
  def to_slim(lvl = nil); end
end
class Hpricot::Elem < Anonymous_Object_26
  def code; end
  def div?; end
  def has_attributes?; end
  def has_class?; end
  def has_id?; end
  def ruby?; end
  def skip_tag_name?; end
  def slim(lvl = nil); end
  def slim_attributes; end
  def slim_class; end
  def slim_id; end
  def slim_ruby_code(r); end
  def to_slim(lvl = nil); end
end
class Hpricot::Doc < Anonymous_Object_26
  def to_slim; end
end
class HTML2Slim::Converter
  def to_s; end
end
class HTML2Slim::HTMLConverter < HTML2Slim::Converter
  def initialize(html); end
end
class HTML2Slim::ERBConverter < HTML2Slim::Converter
  def initialize(file); end
end
