# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/material_icons/all/material_icons.rbi
#
# material_icons-2.2.1
module MaterialIcons
  def self.setup; end
  def self.unicode; end
  def self.unicode=(obj); end
  def unicode; end
  def unicode=(obj); end
end
class MaterialIcons::Engine < Rails::Engine
end
