# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/materialize-sass/all/materialize-sass.rbi
#
# materialize-sass-1.0.0
module Materialize
end
module Materialize::Sass
  def self.assets_path; end
  def self.gem_path; end
  def self.hanami?; end
  def self.javascripts_path; end
  def self.load!; end
  def self.rails?; end
  def self.register_hanami; end
  def self.register_rails_engine; end
  def self.register_sprockets; end
  def self.sprockets?; end
  def self.stylesheets_path; end
end
module Materialize::Helpers
  def toast; end
  def toast_now; end
  def toaster; end
end
module Materialize::Rails
end
class Materialize::Rails::Engine < Rails::Engine
end
